spring:
  application:
    name: retry-service
  profiles:       ## application-{}.yml
    active: @spring.profiles.active@
  cloud:
    loadbalancer:
      retry:
        enabled: true   #启用重试机制

##断路器超时时间: 断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

client-service:
  ribbon:
  ## 只适用ribbon组件, 下面两个注释掉的配置没什么用
#    ConnectTimeout: 250 #请求连接的超时时间
#    ReadTimeout: 3000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 1 #切换实例的重试次数
    MaxAutoRetries: 5 #对当前实例的重试次数, 切换实例的操作不算重试

custom:
  restTemplate:
    connect-timeout: 1000
    connection-request-timeout: 1000
    read-timeout: 3000


