spring:
  application:
    name: hystrix-request
  profiles:       ## application-{}.yml
    active: @spring.profiles.active@

##断路器超时时间: 断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000

feign:
  hystrix:
    enabled: true

ribbon:
  ConnecTimeout: 3000
  ReadTimeout: 5000
  MaxAutoRetries: 2
