server:
  port: 7003
  context-path: /

eureka:
  client:
    service-url:
      #单点配置
      defaultZone: http://eureka1:8001/eureka/


## 如果在zip-server应用中，我们将其端口设置为9411，并且均在本地调试的话，该参数也可以不配置，因为默认值就是http://localhost:9411
spring:
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: 192.168.198.130
    port: 5672
    username: root
    password: root
  sleuth:
    sampler:
      percentage: 1.0 #以请求百分比的方式配置和收集跟踪信息, 默认0.1