server:
  port: 9411
  context-path: /

spring:
  rabbitmq:
    host: 192.168.198.130
    port: 5672
    username: root
    password: root
  sleuth:             #zipkin数据保存到数据库中需要进行如下配置
    enabled: false    #表示当前程序不使用sleuth
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
    schema[0]: classpath:/zipkin.sql        #数据库脚本创建地址，当有多个是可使用 [x] 表示集合第几个元素

zipkin:
  storage:
    type: mysql       #表示 zipkin 数据存储方式是mysql

