server:
  port: 6001
  context-path: /

eureka:
  client:
    service-url:
      #单点配置
      defaultZone: http://eureka1:8001/eureka/

spring:
  rabbitmq:
    host: 192.168.198.130
    port: 5672
    username: root
    password: root
