spring:
  application:
    name: consumer-service

server:
  port: 7002
  context-path: /consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/