spring:
  application:
    name: gateway
  profiles:       ## application-{}.yml
    active: @spring.profiles.active@

zuul:
  ## 过滤敏感词
  sensitive-headers: Cookie,Set-Cookie,Authorization
  routes:
    api-helllo:                     #随便起, 但是要见名知意
      path: /hello-service/**       #随便起, 但是要见名知意, 访问路径: http://localhost:5000/hello-service/hello
      serviceId: hello-service      #不能随便起, 服务名
    api-luck:
      path: /luck-service/**
      serviceId: luck-service

