spring:
  application:
    name: stream-client
  profiles:       ## application-{}.yml
    active: @spring.profiles.active@
  cloud:
    stream:
      bindings:
        stream_client_input:
          group: stream-client
          destination: greetings
